title: Expose Fake Clinics PGH
email: exposefakeclinicspgh@pghdsa.org
description: ''
baseurl: ''
url: 'http://www.exposefakeclinicspgh.com'
twitter_username: pghdsa
github_username:  pghdsa-socfem

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
